---
#start zk nodes
- hosts: "{{zkc}}"
  remote_user: "{{zk_user}}"
  gather_facts: false
  vars_files:
   - "../../roles/zk_install/defaults/main.yml"
   - "../../roles/zk_install/vars/main.yml"
  tasks:
   - name: "start zk nodes"
     shell: >
      {{pub_set_bash}} &&
      cd $ZK_HOME/bin &&
      zkServer.sh start > {{pub_install_log_root}}/zk/zk.log
      executable=/bin/bash

   - name: "waitting..." 
     wait_for: >
      state=started timeout={{zkc_start_timeout}} port={{zk_client_port}} delay={{zkc_start_delay}}
