---
#stop zk nodes
- hosts: "{{zkc}}"
  remote_user: "{{zk_user}}"
  gather_facts: false
  vars_files:
   - "../../roles/zk_install/defaults/main.yml"
   - "../../roles/zk_install/vars/main.yml"
  tasks:
   - name: "stop zk nodes"
     shell: >
      {{pub_set_bash}} &&
      cd $ZK_HOME/bin &&
      zkServer.sh stop
      executable=/bin/bash
      
   - name: "waitting..." 
     wait_for: >
      state=stopped timeout={{zkc_stop_timeout}} port={{zk_client_port}} delay={{zkc_stop_delay}}
