---
- name: "cd dir and tar it"
  shell: >
    cd {{path}} &&
    cd ../ &&
    tar -czvf {{path | basename}}.tar.gz {{path | basename}}
    executable=/bin/bash 

- name: "get xxx.tar.gz to cn"
  fetch: > 
    src={{path}}.tar.gz
    dest={{cntemplet_url}}/{{path | basename}}.tar.gz
    flat=yes

- name: "remove xxx.tar.gz on the remote"
  shell: >
    cd {{path}} &&
    cd ../ &&
    rm {{path | basename}}.tar.gz
    executable=/bin/bash