---
##############################WARNNING###############################
#pub_install default vars
#UNLESS NESSARY, the following configs should NOT be modified
#Generally, we should overwrite it in a group var file.
#####################################################################

#################################
#install configs for apps
#################################
pub_install_app_name:      "syndata"          #eg. "jdk"
pub_install_app_version:   "1.5.20"                  #"1.0.1"
pub_install_type:          "unpack_install"         #unpack_install,copy_install
pub_current_role:          "syndata_install"             #MUST be defined

#custorm config to generate configs for "pub_install"
dfs_install_pkgname:      "{{pub_install_app_name}}-{{pub_install_app_version}}"

#local package file or source path, such as jdk.targ.gz or puppy_web
#todo change it as public default
pub_install_app_src:  "{{pub_install_pkgs_root}}/{{pub_install_app_name}}/{{dfs_install_pkgname}}.tar.gz"

#the final path where the app will be installed to
pub_install_app_home: "{{pub_install_apps_root}}/{{dfs_install_pkgname}}"

pub_install_app_group:     hadoop                     #default user group for app
pub_install_app_user:      hadoop                     #default user name for app

dfs_group: "{{pub_install_app_group}}"
dfs_user: "{{pub_install_app_user}}"

#todo redefine
pub_install_temp_path: "{{pub_install_temp_root}}/{{pub_current_role}}"

#todo redefine.
pub_install_apps_roots:                            #public roots for app install
 - dest: "{{pub_install_synapps_root}}"
 - dest: "{{pub_install_temp_root}}"
   mode: "0755"
 - dest: "{{pub_install_data_root}}"
   mode: "0755"
   user: "hadoop"
   group: "hadoop"

 - dest: "{{pub_install_app_home}}/web/logs"
   mode: "0755"

pub_install_app_templates:                        #list of template files
 - src: "web.yaml"
   dest: "{{pub_install_app_home}}/web/conf/"
 - src: "logging.yaml"
   dest: "{{pub_install_app_home}}/web/conf/"

pub_install_app_paths:                          #list of pre paths
 - dest: "{{pub_install_temp_path}}"
 - dest: "{{pub_install_app_home}}"
   mode: "0755"

pub_install_app_links:                             #list of pre links
 - src: "{{pub_install_app_home}}/web"
   link: "{{pub_install_apps_root}}/syndata_core"

syndata_zip_list:
 - src: "{{pub_install_app_home}}/plibs/syntools-{{pub_install_app_version}}"
   dest: "{{pub_install_app_home}}/plibs"
 - src: "{{pub_install_app_home}}/plibs/jwmphive-{{pub_install_app_version}}"
   dest: "{{pub_install_app_home}}/plibs"
 - src: "{{pub_install_app_home}}/plibs/synhold-{{pub_install_app_version}}"
   dest: "{{pub_install_app_home}}/plibs"

synhold_ik_ext_files:
 - src: "{{pub_install_app_home}}/jlibs/synhold-ik-ext/*"
   dest: "{{pub_install_apps_root}}/es/plugins/ik-analyzer"