---
- include: "useradd.yml"
  vars:
   hosts: "{{hosts}}"
   user: hadoop
   pwd: hadoop

- include: "ntpsvr.yml"
  vars:
   ntps: ntp_servers
  tags: 
    - ntp

- include: "ntpclient.yml"
  vars:
   ntps: ntp_servers
   ntpc: ntp_clients
  tags: 
    - ntpclient

- include: "../java/java_install.yml"
  vars:
   hosts: "{{hosts}}"

- name: "chown" 
  hosts: "{{hosts}}"
  remote_user: root
  gather_facts: false
  tasks:
   - name: "chown /var/syndata"
     shell: >
      chown -R hadoop:hadoop /var/syndata
      executable=/bin/bash
  vars:
   hosts: "{{hosts}}"

- name: "chmod /tmp" 
  hosts: "{{hosts}}"
  remote_user: root
  gather_facts: false
  tasks:
   - name: "chmod 777 /tmp"
     shell: >
      chmod 777 /tmp
      executable=/bin/bash
  vars:
   hosts: "{{hosts}}"

- include: "ulimited.yml"
  vars:
   hosts: "{{hosts}}"