---
##############################WARNNING###############################
#pub_install default vars
#UNLESS NESSARY, the following configs should NOT be modified
#Generally, we should overwrite it in a group var file.
#####################################################################

#################################
#install configs for apps
#################################
pub_install_app_name:      "hive"                  #eg. "jdk"
pub_install_app_version:   "1.2.1"                 #"1.0.1"
pub_install_type:          "unpack_install"         #unpack_install,copy_install
pub_current_role:          "hive_install"          #MUST be defined

#custorm config to generate configs for "pub_install"
hive_install_pkgname:      "{{pub_install_app_name}}-{{pub_install_app_version}}"

#local package file or source path, such as jdk.targ.gz or puppy_web
#todo change it as public default
pub_install_app_src:  "{{pub_install_pkgs_root}}/{{pub_install_app_name}}/{{hive_install_pkgname}}.tar.gz"

#the final path where the app will be installed to
pub_install_app_home: "{{pub_install_apps_root}}/{{hive_install_pkgname}}"

pub_install_app_group:     hadoop                     #default user group for app
pub_install_app_user:      hadoop                     #default user name for app

#todo redefine
pub_install_temp_path: >
 {{pub_install_temp_root}}/{{pub_current_role}}

#todo redefine.
pub_install_apps_roots:                            #public roots for app install
 - dest: "{{pub_install_apps_root}}"
 - dest: "{{pub_install_temp_root}}"

pub_install_app_paths:                           #list of pre paths
 - dest: "{{pub_install_temp_path}}"
 - dest: "{{hive_home}}"
 - dest: "{{pub_install_data_root}}"
 - dest: "{{pub_install_log_root}}/hive"

#system ENV template file, in templates folder
#pub_install_app_envfile: "../../roles/java_install/templates/syn_javaenv.sh"
pub_install_app_envfile: "syn_hiveenv.sh"

pub_update_app_files:
 - src: "mysql-connector-java-5.1.6.jar"
   dest: "{{pub_install_app_home}}/lib"   

pub_install_app_templates:                        #list of template files
 - src: "hive-env.sh"
   dest: "{{pub_install_app_home}}/conf/hive-env.sh"
 - src: "hive-log4j.properties"
   dest: "{{pub_install_app_home}}/conf/hive-log4j.properties"
 - src: "webhcat-site.xml"
   dest: "{{pub_install_app_home}}/hcatalog/etc/webhcat/webhcat-site.xml"
 - src: "hive-site.xml"
   dest: "{{pub_install_app_home}}/conf/hive-site.xml"

#
pub_install_app_links:                             #list of pre links
- src: "{{hive_home}}"
  link: "{{pub_install_apps_root}}/hive"