---
##############################WARNNING###############################
#hbase default vars
#UNLESS NESSARY, the following configs should NOT be modified
#Generally, we should overwrite it in a group var file.
#####################################################################

hive_log_dir:          "{{pub_install_log_root}}/hive"
hive_home:             "{{pub_install_app_home}}"
#hive_data_home:        "{{pub_install_data_root}}/hive_data"
hive_user:              hadoop
hive_group:             hadoop

##################################
##hive runtime configs
##################################
hive_server_port:       10000
hive_start_timeout:     90
hive_start_delay:       3
hive_stop_timeout:      90
hive_stop_delay:        3 

webhcat_server_port:       50111
webhcat_start_timeout:     90
webhcat_start_delay:       3
webhcat_stop_timeout:      90
webhcat_stop_delay:        3 


##################################
##hive default xml
##################################
mapred_reduce_tasks:                        -1
hive_exec_reducers_bytes_per_reducer:       1000000000
hive_exec_reducers_max:                     999
hive_cli_print_header:                      'false'
hive_cli_print_current_db:                  'false'
hive_cli_prompt:                            hive
hive_cli_pretty_output_num_cols:            -1
hive_exec_scratchdir:                       '/tmp/hive-${user.name}'
hive_exec_local_scratchdir:                 '/tmp/${user.name}'
hive_test_mode:                             'false'
hive_test_mode_prefix:                      '_test'
javax_jdo_option_ConnectionURL:             'jdbc:derby:;databaseName=metastore_db;create=true'
javax_jdo_option_ConnectionDriverName:      'org.apache.derby.jdbc.EmbeddedDriver'
hive_tar_gz:                                'apache-hive-0.13.1-bin.tar.gz'