---
- hosts: "{{esc}}"
  remote_user: "{{es_user}}"
  gather_facts: false
  vars_files:
   - "../../roles/es_install/defaults/main.yml"
   - "../../roles/es_install/vars/main.yml"
  tasks:
   - name: "stop es nodes"
     shell: >
      {{pub_set_bash}} && jps -l | grep elasticsearch | awk '{system("kill "$1)}'
      executable=/bin/bash
