---
##############################WARNNING###############################
#pub_install default vars
#UNLESS NESSARY, the following configs should NOT be modified
#Generally, we should overwrite it in a group var file.
#####################################################################

#################################
#install configs for apps
#################################
pub_install_app_name:      "azkaban"                  #eg. "jdk"
pub_install_app_version:   "2.6.4"                    #"1.0.1"
pub_install_type:          "unpack_install"           #unpack_install,copy_install
pub_current_role:          "azkaban_install"         #MUST be defined

#custorm config to generate configs for "pub_install"
azkaban_install_pkgname:    "{{pub_install_app_name}}-{{pub_install_app_version}}"

#local package file or source path, such as jdk.targ.gz or puppy_web
#todo change it as public default
pub_install_app_src:  "{{pub_install_pkgs_root}}/{{pub_install_app_name}}/{{azkaban_install_pkgname}}.tar.gz"

#the final path where the app will be installed to /usr/lib/azkaban
pub_install_app_home: "{{pub_install_apps_root}}/{{azkaban_install_pkgname}}"

pub_install_app_group:     hadoop                     #default user group for app
pub_install_app_user:      hadoop                     #default user name for app

#todo redefine
pub_install_temp_path: >
 {{pub_install_temp_root}}/{{pub_current_role}}

pub_install_app_paths:                           #list of pre paths
 - dest: "{{pub_install_temp_path}}"
 - dest: "{{azkaban_home}}"
 - dest: "{{pub_install_log_root}}/azkaban"

#todo redefine.
pub_install_apps_roots:                            #public roots for app install
 - dest: "{{pub_install_apps_root}}"
 - dest: "{{pub_install_temp_root}}"
   mode: "0755"

pub_install_app_templates:                        #list of template files
 - src: "azkaban.properties"
   dest: "{{pub_install_app_home}}/conf/"
 - src: "azkaban-users.xml"
   dest: "{{pub_install_app_home}}/conf/"
 - src: "commonprivate.properties"
   dest: "{{pub_install_app_home}}/plugins/jobtypes/"
 - src: "commonprivate.properties"
   dest: "{{pub_install_app_home}}/plugins/viewer/hdfs/conf/"


pub_install_app_links:                             #list of pre links
- src: "{{azkaban_home}}"
  link: "{{pub_install_apps_root}}/azkaban"