# This is a configuration file for initailizing logging module and is build based on python 2.7 manuals.
# Format in this file is according to ConfigParser functionality as the python 2.7 manuals said.
# To config this file, you should be likely to read logging.config module docs in python manuals.
version: 1

formatters:
    simpleFormatter:
        format: '%(asctime)s - %(name)s - [%(levelname)s]: %(message)s - [%(filename)s:%(lineno)s]'

handlers:
    console:
        class: logging.StreamHandler
        level: NOTSET
        formatter: simpleFormatter
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        level: NOTSET
        formatter: simpleFormatter
        filename: logs/app.log
        mode: a #append
    rotatingFile:
        class: logging.handlers.RotatingFileHandler
        level: NOTSET
        formatter: simpleFormatter
        filename: logs/app.log
        mode: a
        maxBytes: 52428800
        backupCount: 3
        encoding: UTF-8

loggers:
    console:
        level: NOTSET
        handlers: [console]
        formatter: simpleFormatter
        qualname: console
        propagate: 0
    file:
        level: NOTSET
        handlers: [file]
        formatter: simpleFormatter
        qualname: file
        propagate: 0
    rotatingFile:
        level: NOTSET
        handlers: [rotatingFile]
        formatter: simpleFormatter
        qualname: rotatingFile
        propagate: 0

root:
    level: NOTSET
    handlers: [console, rotatingFile]
    formatter: simpleFormatter