---
- name: remove ssh key on the remote host for user
  authorized_key: user="{{user}}"
                  key="{{lookup('file','~/.ssh/id_rsa.pub')}}"
                  state=absent
                  unique=yes

- name: remote user
  user: name="{{user}}" state=absent remove=yes


